"""CR_5lb_Ch6 — 나머지 17개 CR 문제 추가 (Q5, Q6, Q16~Q19, Q28, Q41, Q42, Q44~Q47, Q50, Q51, Q53, Q54)"""
import json
from pathlib import Path

DATA_FILE = Path(__file__).parent / "gre_content" / "practice_questions.json"


def cr(qid, passage, stem, a, b, c, d, e, correct, diff="medium"):
    return {
        "id": qid, "section": "verbal", "type": "critical_reasoning",
        "subtype": "cr", "difficulty": diff, "set": None,
        "passage": passage, "stem": stem,
        "blanks": [{"label": "Blank", "choices": {"A": a, "B": b, "C": c, "D": d, "E": e}}],
        "correct": [correct], "explanation": "", "source": "CR_5lb_Ch6",
    }


questions = [

# ── Q5 ──────────────────────────────────────────────────────────────────────
cr("CR5LB_05",
   "A recent decline in the employment rate was spurred by predictions of slow economic growth in "
   "the coming year. However, these predictions would not have affected the employment rate if major "
   "industries had not lacked capital reserves. So if major industries increase their capital reserves, "
   "the employment rate will not decline in the future.",
   "Which of the following, if true, most seriously calls into question the conclusion of the argument above?",
   "Major industries foresaw the drop in employment.",
   "Some major industries had appreciable capital reserves.",
   "The government could encourage major industries to maintain sufficient capital reserves.",
   "The government could pass legislation mandating that major industries set aside a fixed amount "
   "as capital reserves every year.",
   "The drop in the employment rate was more severe this year than last.",
   "B"),

# ── Q6 ──────────────────────────────────────────────────────────────────────
cr("CR5LB_06",
   "New methods of math education in this country do a disservice to our children. In the lower "
   "grades, math instruction should focus on the basic skills that students will need in higher grades. "
   "Learning basic math skills is like learning the scales and chords that one will later need to play "
   "the piano. Math educators in this country seem to have it backward: beginning in higher grades the "
   "same narrow, skills-based approach that students needed in lower grades, rather than the analytical "
   "tools that they will need to solve complex math problems.",
   "Which of the following, if true, would most seriously weaken the conclusion drawn above?",
   "While math courses are often required in elementary school and high school, such classes are "
   "rarely taught at the college level.",
   "On international tests of complex math skills, high school students in this country performed "
   "worse than they used to, relative to their counterparts in countries in which problem-solving "
   "is emphasized in higher grades.",
   "When presented with a math problem to solve, students in higher grades are more likely to arrive "
   "at different answers than students in lower grades.",
   "Older students tend to receive higher grades in math than younger students do.",
   "Universities report a steady increase in the qualifications of applicants from this country "
   "who apply for courses that require analytical skills and advanced math.",
   "E"),

# ── Q16 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_16",
   "Due to high jet fuel costs, airline carriers are looking for new ways to increase revenues and "
   "thereby counteract declining profits. Airline A has proposed increasing the number of standing "
   "room only 'seats' in which passengers would be packed into a plane as safely as possible. "
   "According to the proposal, since it relates to passenger safety, this arrangement cannot be "
   "implemented without prior approval by the Federal Aviation Administration.",
   "The above statements, if true, indicate that which of the following has been concluded by Airline A?",
   "The addition of standing room only 'seats' will generate more revenue than the cost of ensuring "
   "that these seats meet all safety requirements.",
   "The Federal Aviation Administration will approve Airline A's specific proposal.",
   "The revenue generated by the addition of standing room 'seats' is greater than the current "
   "cost of jet fuel.",
   "There are no safe ways in which Airline A can increase revenues.",
   "Passenger safety is less important than increasing revenue.",
   "A"),

# ── Q17 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_17",
   "According to a recent study, more than 50% of graduates of the private high schools in a certain "
   "county continue their education and are admitted to college and subsequently pursue college "
   "education. Therefore, if parents in the county wish to maximize the likelihood that their children "
   "will attend college, they should send them to private schools rather than public schools.",
   "Which of the following statements, if true, would most seriously weaken the argument above?",
   "Graduates of private schools typically score higher on standardized tests and other tests of "
   "academic achievement.",
   "While private schools are typically very expensive, attendance at public school is free for the "
   "residents of the county.",
   "In comparison with graduates of private schools, a substantially greater proportion of public "
   "school graduates receive need-based financial aid for their college education.",
   "In comparison to private schools, public schools provide more opportunities for student involvement "
   "in sports and other athletic activities, which almost always increase the likelihood of students "
   "making new social friends.",
   "Most public schools are located in rural areas of the county populated primarily by farmers; "
   "nearly 50% of students from public high schools choose to pursue farming occupations rather "
   "than apply to colleges.",
   "E"),

# ── Q18 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_18",
   "Two years ago, the cost of the raw material used in a particular product doubled after an "
   "earthquake disrupted production in the region where the material is mined. Since that time, "
   "the company that makes the product has seen its profit margins decline steadily. Aiming to "
   "improve profit margins, the company's board of engineers has decided that it must find a new "
   "source for the raw material.",
   "Which of the following, if true, would cast the most doubt on the validity of the engineers' decision?",
   "New competitors have entered the market every six months for the past two years, resulting in "
   "price wars that have progressively driven down revenues across the market.",
   "Although the earthquake occurred two years ago, the region's mines have still not recovered "
   "to pre-earthquake production capacity.",
   "There are several other regions from which the raw material can be mined, but those regions "
   "do not produce as much of the raw material as the current source region.",
   "The company could use a completely different raw material to make its product.",
   "Recent advances in mining technology will make mining the raw material much more efficient "
   "and cost-effective in the future.",
   "A"),

# ── Q19 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_19",
   "A recent development in the marketplace for consumer technology goods has been the premium "
   "placed on design—products with innovative and appealing designs relative to competing products "
   "often command substantially higher prices. However, some technology design innovations are "
   "quickly copied by other manufacturers. Though many consumer technology companies charge as much "
   "as possible to extract maximum value from their new designs, large profits generated by the "
   "innovative design will give competitors stronger incentives to copy the designs. Therefore, "
   "the best strategy to extract the greatest profit from an innovative new design is to charge "
   "less than the greatest possible price.",
   "In the argument above, the two boldface portions play which of the following roles?",
   "The first is an assumption that assists a course of action stressed by the argument; the second "
   "presents an alternative strategy endorsed by the argument.",
   "The first provides a factual basis that supports a particular course of action; the second "
   "is the strategy that the argument recommends.",
   "The first is a consideration presented to demonstrate that a particular strategy will not apply; "
   "the second is a factor cited to support a contrasting strategy.",
   "The first is a factor cited to support a particular strategy; the second is a contrasting strategy.",
   "The first is a relevant consideration presented to demonstrate that a particular strategy will "
   "not apply; the second is the argument against that strategy.",
   "B"),

# ── Q28 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_28",
   "An oil field prospector and developer reported a large oil deposit in southwestern Texas. As a "
   "result, a large oil and gas company purchased the field with the intention of drilling oil wells "
   "in the area soon afterwards. However, the company found that the oil deposit was actually much "
   "smaller than the prospector had indicated. Thus, the methods that the prospector had used to "
   "determine the size of the oil deposit must have been inaccurate.",
   "Which of the following is an assumption on which the argument depends?",
   "The company's methods of measuring the size of the oil deposit were determined by a third party "
   "to be more accurate than those used by the prospector.",
   "The prospector did not purposefully fabricate or misrepresent the size of the oil deposit.",
   "Though smaller than originally thought, the oil deposit contained enough oil to make drilling "
   "profitable.",
   "The prospector did not explore other oil fields and use the same methods to determine the "
   "magnitude of the oil present, if any.",
   "The company had successfully drilled for oil in other large oil fields in Texas throughout "
   "the early 20th century.",
   "B"),

# ── Q41 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_41",
   "In an attempt to discover the cause of malaria, a deadly infectious disease common in tropical "
   "areas, early European settlers in Hong Kong attributed the malady to poisonous gases supposed "
   "to be emanating from the feng valley, where Hong Kong was situated. They called it 'bad air.' "
   "In fact, the disease is actually caused by a specific parasite. The female of the species can "
   "carry a parasitic protozoa that is passed on to unsuspecting humans who are bitten.",
   "What functions do the two boldface statements serve in the passage?",
   "The first follows from a mistaken conclusion about a topic in question; the second explicates "
   "the correct explanation for the topic.",
   "The first provides an initial conjecture; the second presents evidence that contradicts "
   "that conjecture.",
   "The first serves to investigate a common assumption; the second offers confirmation of "
   "that assumption.",
   "The first describes the cause of an erroneous conclusion; the second develops a premise to "
   "support the correct conclusion.",
   "The first presents a point about the original, and incorrect, school of thought; the second "
   "provides the judgment later found to be true.",
   "A"),

# ── Q42 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_42",
   "Government restrictions have severely limited the amount of stem cell research companies in "
   "the United States can conduct. Because of these restrictions, many scientists previously based "
   "in the United States and specializing in the field of stem cell research have signed long-term "
   "contracts to work for foreign companies. Recently, Congress has proposed lifting all restrictions "
   "on stem cell research.",
   "Which of the following conclusions can most properly be inferred from the information above?",
   "At least some foreign companies that conduct stem cell research work under fewer restrictions "
   "than some United States companies do.",
   "Because scientists previously based in the U.S. are under long-term contracts to foreign "
   "companies, there will be no immediate return of these professionals into the United States.",
   "In all parts of the world, stem cell research is dependent on the financial backing of "
   "local government.",
   "In the near future, U.S. companies will once again be at the forefront of stem cell research.",
   "If restrictions on stem cell research are lifted, many of the scientists previously based in "
   "the United States will break their contracts to return to U.S. companies.",
   "A"),

# ── Q44 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_44",
   "Dengue fever is a viral infection transmitted by the Aedes mosquito, whereas malaria is a "
   "parasitic infection transmitted by the Anopheles mosquito. Since both types of mosquito are "
   "prevalent on Singapore's 'Mosquito Coast,' anyone with a compromised immune system should not "
   "travel to this region, particularly during the rainy season.",
   "All of the following, if true, strengthen the argument EXCEPT:",
   "Medicines taken to prevent or treat malaria can cause serious health complications for people "
   "with weak immune systems.",
   "The Nicaraguan government is trying to reduce the number of mosquitoes on the Mosquito Coast.",
   "A compromised immune system has difficulty fighting either viral or parasitic infections.",
   "During the rainy season, the populations of both Aedes and Anopheles mosquitoes multiply "
   "in the Mosquito Coast.",
   "The most effective chemical insect repellent has been shown to cause brain damage upon "
   "repeated application to the skin.",
   "B"),

# ── Q45 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_45",
   "In 2001, the Peruvian government began requiring tourists to buy expensive permits to hike the "
   "remote Inca Trail, which goes to the ancient city of Machu Picchu. The total number of permits "
   "is strictly limited; in fact, only 500 people per day are now allowed to hike the Inca Trail, "
   "whereas before 2001, visitors numbered in the thousands. The stated purpose of the program is "
   "to preserve the archaeological treasures along the Inca Trail.",
   "Which of the following, if true, most strengthens the argument that the program has successfully "
   "prevented deterioration of archaeological treasures along the Inca Trail?",
   "Since 2001, hotels near Machu Picchu have experienced declines in income, as fewer tourists "
   "means fewer sales of craft goods and refreshments.",
   "Since 2001, the sale of Inca Trail permits is used to staff a museum of Incan culture in "
   "Peru's capital city, Lima, and to hire guards for archaeological sites without permit programs.",
   "Since 2001, Incan ruins similar to Machu Picchu but not on the Inca Trail have deteriorated "
   "at a significantly greater rate than those on the trail.",
   "The total number of tourists visiting Peru has risen substantially since 2001, even as the "
   "number of tourists hiking the Inca Trail has remained constant.",
   "The Peruvian government has used revenue from Inca Trail permits to fund restoration efforts "
   "at other historical sites throughout the country.",
   "D"),

# ── Q46 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_46",
   "The Farmacy Center for the Performing Arts, designed by a world-renowned architect, was built "
   "15 years ago in downtown Metropolis. A recent study shows that, on average, a person who attends "
   "a performance at the Farmacy Center spends $83 at downtown businesses on the day of the "
   "performance. Following this report, the chairman of the Farmacy Center's Board of Trustees "
   "claims that the Farmacy Center has been a significant source of the economic revitalization "
   "of downtown Metropolis.",
   "Which of the following, if true, most properly supports the chairman's contention?",
   "The Metropolis Chamber of Commerce honored the Farmacy chairman this year for his contributions "
   "to the city.",
   "Restaurants near the Farmacy Center tend to be more expensive than restaurants in outlying areas.",
   "The Farmacy Center is the only building in Metropolis designed by a world-renowned contemporary "
   "architect.",
   "For major theater companies on national tours, the Farmacy Center is the first choice among "
   "venues in downtown Metropolis.",
   "Many suburbanites visit downtown Metropolis on weekends in order to see performances at "
   "the Farmacy Center.",
   "E"),

# ── Q47 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_47",
   "One retirement account option allows a worker to save money without paying taxes, but requires "
   "the worker to pay taxes on funds withdrawn from the account upon retirement. A second option "
   "requires the worker to pay taxes upfront, but allows the worker to withdraw funds tax-free upon "
   "retirement. Assuming the rate of return available in the worker's retirement account at retirement "
   "is higher than the total amount contributed prior to retirement, workers can expect to pay less "
   "in taxes overall if they choose the second option.",
   "Which of the following pieces of information would be most useful in determining whether "
   "the conclusion is valid for an individual worker?",
   "The amount of money the worker will contribute to the retirement plan over his or her career.",
   "The amount that tax rates will increase in the future.",
   "Whether inflation will be lower than the retirement account's annual earnings.",
   "How the worker's tax bracket in retirement compares to his or her tax bracket while "
   "still employed.",
   "The dollar value of the worker's account upon retirement.",
   "D"),

# ── Q50 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_50",
   "Male CEOs of major corporations are, on average, three inches taller than the average male. "
   "When data from the general population are analyzed and corrected for gender and age, a clear "
   "pattern emerges: for every extra inch of height, a person's annual salary increases by "
   "approximately $789. Citing these facts, a prominent journalist claims that most employers have "
   "an unconscious bias in favor of tall people.",
   "Which of the following, if true, would most seriously undermine the journalist's argument?",
   "On average, a woman is shorter than her husband and earns less than he does.",
   "Socioeconomic status has been shown to have a strong positive correlation to both height "
   "and educational attainment.",
   "Professional basketball players, who are some of the tallest people in the labor force, "
   "have high incomes.",
   "Human resources professionals, who make many hiring decisions, are on average no taller "
   "than the general population.",
   "People who are taller than average tend to project greater confidence in professional settings.",
   "B"),

# ── Q51 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_51",
   "Traditionally, public school instructors have been compensated according to seniority. Recently, "
   "the existing salary system has been increasingly criticized as an approach to compensation that "
   "rewards longevity in teaching and ignores instructional quality. Instead, educational experts "
   "argue that, to retain exceptional teachers and maintain quality instruction, teachers should "
   "receive salaries or bonuses based on merit, rather than seniority.",
   "Which of the following, if true, most strengthens the conclusion of the educational experts?",
   "Some teachers believe that financial compensation is not the only factor contributing to job "
   "satisfaction and teaching performance.",
   "School districts will develop their own unique compensation structures that may differ greatly "
   "from those of other school districts.",
   "Upon leaving the teaching profession, many young teachers cite a lack of opportunity for more "
   "rapid financial advancement as a primary factor in their decisions to change careers.",
   "In school districts that have implemented pay-for-performance compensation structures, "
   "standardized test scores have dramatically increased.",
   "The average salary of public school teachers has not kept pace with inflation over "
   "the past decade.",
   "D"),

# ── Q53 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_53",
   "According to a study of more than 50,000 Norwegian smokers, smokers who reduced their nicotine "
   "intake from cigarettes, even by up to 50%, did not achieve significant health benefits. The "
   "mortality rate for those who cut back on cigarettes was not lower than that for heavier smokers. "
   "Moreover, the rate of cardiovascular disease was similar across all subsets of smokers in the "
   "study. As a result, the authors of the study claim that reducing nicotine intake does not "
   "improve one's health.",
   "Which of the following, if true, most seriously jeopardizes the findings of the study "
   "described above?",
   "The majority of study participants minimized their nicotine withdrawal symptoms through the "
   "use of nicotine patches and other nicotine replacement therapy products.",
   "Many of the study's participants periodically dined in restaurants in which smoking "
   "was permitted.",
   "Most study participants started smoking at a young age and smoked without taking breaks.",
   "Quitting smoking entirely results in a marked reduction in the ill effects of smoking.",
   "Men and women who smoked pipes and cigars were excluded from the study.",
   "A"),

# ── Q54 ─────────────────────────────────────────────────────────────────────
cr("CR5LB_54",
   "In developed countries, such as Canada, the percentage of the population diagnosed with clinical "
   "depression is much greater than that in developing countries. Researchers hypothesize that this "
   "difference is due to the increased leisure time afforded to residents of developed countries.",
   "The hypothesis of the researchers depends on which of the following assumptions?",
   "Clinical depression is a genetically transmitted malady.",
   "Access to accurate diagnostic procedures for depression is equal for residents of developing "
   "and developed countries.",
   "Certain medications that effectively treat clinical depression are not readily available "
   "in developing countries.",
   "Few residents of developing countries dedicate significant time to leisure activities.",
   "The stress associated with economic hardship in developing countries prevents the onset "
   "of clinical depression.",
   "B"),

]


def main():
    with open(DATA_FILE, encoding="utf-8") as f:
        data = json.load(f)

    if "verbal" not in data:
        data["verbal"] = []

    existing_ids = {q["id"] for q in data["verbal"]}
    new_qs = [q for q in questions if q["id"] not in existing_ids]
    skipped = len(questions) - len(new_qs)

    data["verbal"].extend(new_qs)

    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Added: {len(new_qs)}  |  Skipped(dup): {skipped}")
    print(f"Total verbal: {len(data['verbal'])}")
    cr_count = sum(1 for q in data["verbal"] if q["type"] == "critical_reasoning")
    print(f"CR questions: {cr_count}")


if __name__ == "__main__":
    main()
